version: "3.8" # Specify the Docker Compose file format version

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: dating_app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "1110:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres-data:
    driver: local
